ARG TILED_VERSION=0.2.9
FROM node:20-alpine AS builder

ARG TILED_VERSION

RUN apk add --no-cache git

RUN git clone --depth 1 --branch v${TILED_VERSION} \
        https://github.com/bluesky/tiled.git /tiled

WORKDIR /tiled/web-frontend

RUN npm ci && npm run build -- --base /

FROM nginx:alpine

COPY --from=builder /tiled/web-frontend/dist /usr/share/nginx/html
COPY nginx.frontend.conf /etc/nginx/conf.d/default.conf
